version: '3.3'
networks:
  testNetwork:
    driver: bridge

services:
  Radiance:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=aurinko88
      - POSTGRES_USER=postgres
      - POSTGRES_DB=RadianceDB
    volumes:
      -

        type: bind
        source: ./testData/postgres_data
        target: /var/lib/postgresql/data


    networks:
      - testNetwork

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
    environment:
      - PGADMIN_DEFAULT_EMAIL=default@linux.com
      - PGADMIN_DEFAULT_PASSWORD=key
      - PGADMIN_LISTEN_PORT=5050

    networks:
      - testNetwork
  pgagent:
    image: chiavegatto/postgres-pgagent
    entrypoint: /bin/sh -c
      "/tmp/wait-for-it.sh datascripts-Radiance-1:5432 --timeout=30 &&
      PGPASSWORD='aurinko88' psql -U postgres -h datascripts-Radiance-1 -p 5432 -d RadianceDB -c 'CREATE EXTENSION IF NOT EXISTS pgagent;' &&
      PGPASSWORD='aurinko88' pgagent -f hostaddr=datascripts-Radiance-1 dbname=postgres user=postgres port=5432"
    environment:
      - TIMEZONE=Etc/UTC
    networks:
      - testNetwork