version: '3.3'
networks:
  testNetwork:
    driver: bridge

services:
  Radiance:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=aurinko88
      - POSTGRES_USER=postgres
      - POSTGRES_DB=RadianceDB
    volumes:
      -

        type: bind
        source: ./testData/postgres_data
        target: /var/lib/postgresql/data


    networks:
      - testNetwork

  pgAdmin:
    image: dpage/pgadmin:latest
    ports:
      - '5050:5050'
    networks:
      - testNetwork
