version: '3.3'
networks:
  testNetwork:
    driver: bridge

services:
  Radiance:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD)
      - POSTGRES_USER=${POSTGRES_USER)
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      -

        type: bind
        source: ./testData/postgres_data
        target: /var/lib/postgresql/data


    networks:
      - testNetwork

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}

    networks:
      - testNetwork
